version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: app_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: app_db
    restart: always
    environment:
      POSTGRES_DB: discounthub
      POSTGRES_USER: discounthub_user
      POSTGRES_PASSWORD: secret123
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
