version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm run dev -- --host
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
