"""feat: deal_packages, bookings, subscriptions + lat/lon in discounts

Revision ID: 05ddfe5ab54f
Revises: 7d97607028e5
Create Date: 2025-08-13 22:48:33.597270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05ddfe5ab54f'
down_revision: Union[str, Sequence[str], None] = '7d97607028e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deal_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_packages_id'), 'deal_packages', ['id'], unique=False)
    op.create_index(op.f('ix_deal_packages_title'), 'deal_packages', ['title'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_profile_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('geofence_lat', sa.Float(), nullable=True),
    sa.Column('geofence_lon', sa.Float(), nullable=True),
    sa.Column('geofence_radius_km', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_category_id'), 'subscriptions', ['category_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_store_id'), 'subscriptions', ['store_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_profile_id'), 'subscriptions', ['user_profile_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_profile_id', sa.Integer(), nullable=False),
    sa.Column('discount_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'canceled', 'expired', name='booking_status'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reserved_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['discount_id'], ['discounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_discount_id'), 'bookings', ['discount_id'], unique=False)
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_index(op.f('ix_bookings_user_profile_id'), 'bookings', ['user_profile_id'], unique=False)
    op.add_column('discounts', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('discounts', sa.Column('longitude', sa.Float(), nullable=True))
    op.create_index('ix_discounts_lat_lon', 'discounts', ['latitude', 'longitude'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_discounts_lat_lon', table_name='discounts')
    op.drop_column('discounts', 'longitude')
    op.drop_column('discounts', 'latitude')
    op.drop_index(op.f('ix_bookings_user_profile_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_discount_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_subscriptions_user_profile_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_store_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_category_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_deal_packages_title'), table_name='deal_packages')
    op.drop_index(op.f('ix_deal_packages_id'), table_name='deal_packages')
    op.drop_table('deal_packages')
    # ### end Alembic commands ###
