"""add product model

Revision ID: 5b12e59a3090
Revises: 8bfcc42e713d
Create Date: 2025-07-25 09:29:44.635273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b12e59a3090'
down_revision: Union[str, Sequence[str], None] = '8bfcc42e713d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('url', sa.String(), nullable=True))
    op.drop_constraint(op.f('stores_name_key'), 'stores', type_='unique')
    op.create_index(op.f('ix_stores_name'), 'stores', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stores_name'), table_name='stores')
    op.create_unique_constraint(op.f('stores_name_key'), 'stores', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('stores', 'url')
    # ### end Alembic commands ###
