"""change discount FK to sellers

Revision ID: f7683190fb0a
Revises: fb40b5786ab4
Create Date: 2025-07-24 18:08:36.445986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7683190fb0a'
down_revision: Union[str, Sequence[str], None] = 'fb40b5786ab4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('discounts_seller_id_fkey'), 'discounts', type_='foreignkey')
    op.create_foreign_key(None, 'discounts', 'sellers', ['seller_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'discounts', type_='foreignkey')
    op.create_foreign_key(op.f('discounts_seller_id_fkey'), 'discounts', 'users', ['seller_id'], ['id'])
    # ### end Alembic commands ###
