name: Backend CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          cd backend
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Alembic check
        run: |
          cd backend
          alembic upgrade head

      - name: Lint (optional, можно убрать)
        run: |
          cd backend
          pip install flake8
          flake8 .
