name: CI

on:
  pull_request:
    branches: [ "develop", "main" ]
  push:
    branches: [ "develop" ]

jobs:
  backend:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: discounthub
          POSTGRES_USER: discounthub_user
          POSTGRES_PASSWORD: secret123
        ports: [ "5432:5432" ]
        options: >-
          --health-cmd="pg_isready -U discounthub_user -d discounthub"
          --health-interval=5s --health-timeout=5s --health-retries=20
    env:
      DATABASE_URL: postgresql+psycopg2://discounthub_user:secret123@localhost:5432/discounthub
      PYTHONWARNINGS: ignore
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y build-essential libpq-dev

      - name: Install Python deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install pytest pytest-cov alembic

      - name: Wait for Postgres
        run: |
          for i in {1..60}; do
            pg_isready -h localhost -p 5432 -U discounthub_user && break
            sleep 1
          done

      - name: Run Alembic migrations
        env:
          ALEMBIC_CONFIG: alembic.ini
        run: alembic upgrade head

      - name: Pytest (cov ≥70%)
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pytest -q --maxfail=1 --disable-warnings --cov=app --cov-report=term-missing --cov-fail-under=70

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build
