name: CI

on:
  push:
    branches: [ main, develop, ci/** ]
  pull_request:
    branches: [ main, develop ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  backend:
    name: Backend (tests)
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: discounthub_test
          POSTGRES_USER: discounthub
          POSTGRES_PASSWORD: discounthub
        ports:
          - 5432:5432
        # ВАЖНО: без healthcheck — будем ждать БД вручную
        # options: (удалено)

    env:
      DATABASE_URL: postgresql+psycopg2://discounthub:discounthub@localhost:5432/discounthub_test
      PYTHONUNBUFFERED: "1"
      PYTHONPATH: ${{ github.workspace }}/backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev

      - name: Install Python deps
        working-directory: backend
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Wait for Postgres
        env:
          PGPASSWORD: discounthub
        run: |
          for i in {1..60}; do
            if pg_isready -h localhost -p 5432 -U discounthub -d discounthub_test; then
              echo "Postgres is ready"; exit 0
            fi
            echo "Waiting for Postgres ($i/60)..."; sleep 2
          done
          echo "Postgres is not ready in time"; exit 1

      - name: Run tests
        working-directory: backend
        run: pytest -q

  frontend:
    name: Frontend (install & build)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          # cache: "npm"  # УБРАНО: нет lock-файла

      - name: Install deps
        working-directory: frontend
        run: |
          npm install --no-audit --no-fund

      - name: Build (optional)
        working-directory: frontend
        run: |
          npm run -s build || echo "No build script, skipping"
